CREATE TABLE  `nv_members` (
  `id_member` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `member_name` varchar(80) NOT NULL DEFAULT '',
  `passwd` varchar(64) NOT NULL DEFAULT '',
  `real_name` varchar(255) NOT NULL DEFAULT '',
  `email_address` varchar(255) NOT NULL DEFAULT '',
  `birthdate` date NOT NULL DEFAULT '0001-01-01',
  `gender` tinyint(4) unsigned NOT NULL DEFAULT '0',
  `date_regis` int(10) unsigned NOT NULL DEFAULT '0',
  `id_facebook` bigint(20) unsigned NOT NULL DEFAULT '0',
  `link_facebook` varchar(255) NOT NULL DEFAULT '',
  `last_login` int(10) unsigned NOT NULL DEFAULT '0',
  `instant_messages` smallint(5) NOT NULL DEFAULT '0',
  `unread_messages` smallint(5) NOT NULL DEFAULT '0',
  `avatar` varchar(255) NOT NULL DEFAULT '',
  `notify_news` tinyint(4) NOT NULL DEFAULT '1',
  `member_ip` varchar(255) NOT NULL DEFAULT '',
  `member_ip2` varchar(255) NOT NULL DEFAULT '',
  `is_activated` tinyint(3) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_member`),
  KEY `member_name` (`member_name`),
  KEY `real_name` (`real_name`),
  KEY `date_regis` (`date_regis`),
  KEY `last_login` (`last_login`)
) ENGINE=Innodb AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;